stages:
    - build
    - package
    - test
    - e2e
    - cleanup
    - release
    
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_IMAGE_TAGGED: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

cache:
  paths:
    - .cache/pip
    - venv/

build:
    stage: build
    image: python:3.8-alpine
    script:
        - python --version
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install -r requirements.txt

containerize:
  stage: package
  image: docker:20.10.17-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAGGED .
    - docker push $DOCKER_IMAGE_TAGGED
  after_script:
    - docker rmi $DOCKER_IMAGE_TAGGED

unit-test:
  stage: test
  image: python:3.8-alpine
  script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python3 -m unittest

e2e:
  stage: e2e
  image: python:3.8-alpine
  script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python3 -m behave

remove-container:
  stage: cleanup
  image: docker:20.10.15-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - wget -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.16.0/reg-linux-amd64
    - chmod +x /usr/bin/reg
    - reg rm $DOCKER_IMAGE_TAGGED
  except:
    variables:
      - $CI_COMMIT_TAG

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG != null
      when: manual
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - release-cli create
        --name "connect-4-${CI_COMMIT_TAG}"
        --description "A docker image is available at $DOCKER_IMAGE_TAGGED"
        --tag-name "${CI_COMMIT_TAG}"

    










